services:
  dash-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev 
    container_name: mi_app_desarrollo
    ports:
      - "8050:8050"
    volumes:
      - ./app:/app
    environment:
      - DASH_DEBUG=true
    # command: python app.py
    command: uvicorn main:app --host 0.0.0.0 --port 8050 --reload
    
    # LIMITACIÃ“N DE RECURSOS
    deploy:
      resources:
        limits:
          memory: 8G     
          cpus: '2.0'    
        reservations:
          memory: 1G     
    restart: unless-stopped